# roles/docker/tasks/main.yml
# Install docker
# https://docs.docker.com/engine/install/ubuntu/

- name: Install required system packages
  apt:
    name:
      - ca-certificates
      - curl
      - lsb-release
    state: latest

- name: Make sure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Add Docker GPG apt Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Gather arch
  shell: dpkg --print-architecture
  register: arch
  changed_when: False

- name: Gather release
  shell: lsb_release -cs
  register: release
  changed_when: False

- name: Output
  debug:
    msg: "Architecture: {{ arch.stdout }}, Release: {{ release.stdout }}"

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
    state: present
    filename: docker

- name: Update apt and install docker-ce
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Add the user to the docker group
  user:
    name: "{{user}}"
    groups: docker
    append: yes
